frrk8s:
  enabled: false
controller:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
speaker:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist
  resources:
    requests:
      cpu: 30m
      memory: 64Mi
    limits:
      memory: 256Mi
  frr:
    enabled: false
