{
 "title": "Kubernetes / Compute Resources / Pod",
 "tags": [
  "kubernetes-mixin",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": ".*" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\",cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\",pod=\"$pod\",cluster=~\"$cluster\",container!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"}) by(cluster)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"}) by(cluster)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\",cluster=~\"$cluster\"}[$__rate_interval])) by(container,cluster) / sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\",cluster=~\"$cluster\"}[$__rate_interval])) by(container,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"$namespace\",pod=\"$pod\",cluster=~\"$cluster\",container!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster) / sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster) / sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"}) by(cluster)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"}) by(cluster)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",image!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster) / sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container)) by(container,cluster) / sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(container_memory_rss{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\",container!=\"POD\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(container_memory_cache{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\",container!=\"POD\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    },
    {
     "expr": "sum(max(container_memory_swap{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"\",container!=\"POD\"}) by(cluster,namespace,pod,container)) by(container,cluster)"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(8 * irate(container_network_receive_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(8 * rate(container_network_transmit_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS (Pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "ceil(sum(rate(container_fs_reads_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster))",
     "legendFormat": "Reads"
    },
    {
     "expr": "ceil(sum(rate(container_fs_writes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "ThroughPut (Pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "IOPS (Containers)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "ceil(sum(rate(container_fs_reads_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by(container,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ThroughPut (Containers)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by(container,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by(container,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_writes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by(container,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_reads_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by(container,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by(container,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by(container,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by(container,cluster)"
    }
   ]
  }
 ]
}