{
 "title": "Kubernetes / Compute Resources / Workload",
 "tags": [
  "kubernetes-mixin",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": ".*" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\",cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "type",
    "label": "workload_type",
    "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\"}, workload_type)"
   },
   {
    "name": "workload",
    "label": "workload",
    "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload_type=~\"$type\"}, workload)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(max(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"cpu\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster) / sum(max(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"cpu\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(max(kube_pod_container_resource_limits{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"cpu\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster) / sum(max(kube_pod_container_resource_limits{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"cpu\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(max(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"memory\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster) / sum(max(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"memory\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(max(kube_pod_container_resource_limits{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"memory\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster) / sum(max(kube_pod_container_resource_limits{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"memory\"}) by(cluster,namespace,pod,container) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum((8 * rate(container_network_receive_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum((8 * rate(container_network_transmit_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum((8 * rate(container_network_receive_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum((8 * rate(container_network_transmit_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Pod: Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg((8 * rate(container_network_receive_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Pod: Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg((8 * rate(container_network_transmit_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\"$workload\",workload_type=~\"$type\"}) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}