{
 "title": "Kubernetes / Compute Resources / Namespace (Pods)",
 "tags": [
  "kubernetes-mixin",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": ".*" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\",cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(cluster) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"cpu\"}) by(cluster)"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(cluster) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"cpu\"}) by(cluster)"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container)) by(cluster) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"memory\"}) by(cluster)"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container)) by(cluster) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",cluster=~\"$cluster\",namespace=\"$namespace\",resource=\"memory\"}) by(cluster)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)",
     "legendFormat": "__auto"
    },
    {
     "expr": "scalar(max(kube_resourcequota{cluster=~\"$cluster\",namespace=\"$namespace\",type=\"hard\",resource=\"requests.cpu\"}) by(cluster))",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(max(kube_resourcequota{cluster=~\"$cluster\",namespace=\"$namespace\",type=\"hard\",resource=\"limits.cpu\"}) by(cluster))",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster) / sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster) / sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)",
     "legendFormat": "__auto"
    },
    {
     "expr": "scalar(max(kube_resourcequota{cluster=~\"$cluster\",namespace=\"$namespace\",type=\"hard\",resource=\"requests.memory\"}) by(cluster))",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(max(kube_resourcequota{cluster=~\"$cluster\",namespace=\"$namespace\",type=\"hard\",resource=\"limits.memory\"}) by(cluster))",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster) / sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(container_memory_working_set_bytes{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\",image!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster) / sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(container_memory_rss{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(container_memory_cache{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(container_memory_swap{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(8 * rate(container_network_receive_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(8 * rate(container_network_transmit_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(8 * rate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(8 * rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "ceil(sum(rate(container_fs_reads_total{container!=\"\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{container!=\"\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container!=\"\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container!=\"\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_writes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_reads_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\",container!=\"\",cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(pod,cluster)"
    }
   ]
  }
 ]
}