{
 "title": "Kubernetes / Compute Resources / Node (Pods)",
 "tags": [
  "kubernetes-mixin",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": ".*" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\",job=\"kube-state-metrics\",node=~\"$node\",resource=\"cpu\"}) by(cluster)",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",job=\"kube-state-metrics\",node=~\"$node\",resource=\"cpu\"}) by(cluster)",
     "legendFormat": "max allocatable"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster) / sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster) / sum(max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    }
   ]
  },
  {
   "title": "Memory Usage (w/cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\",job=\"kube-state-metrics\",node=~\"$node\",resource=\"memory\"}) by(cluster)",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",job=\"kube-state-metrics\",node=~\"$node\",resource=\"memory\"}) by(cluster)",
     "legendFormat": "max allocatable"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\",node=~\"$node\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\",job=\"kube-state-metrics\",node=~\"$node\",resource=\"memory\"}) by(cluster)",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",job=\"kube-state-metrics\",node=~\"$node\",resource=\"memory\"}) by(cluster)",
     "legendFormat": "max allocatable"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_memory_rss{cluster=~\"$cluster\",node=~\"$node\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\",node=~\"$node\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\",node=~\"$node\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster) / sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\",node=~\"$node\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster) / sum(max(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=~\"$cluster\",node=~\"$node\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_memory_rss{cluster=~\"$cluster\",node=~\"$node\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_memory_cache{cluster=~\"$cluster\",node=~\"$node\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    },
    {
     "expr": "sum(max(node_namespace_pod_container:container_memory_swap{cluster=~\"$cluster\",node=~\"$node\",container!=\"\"}) by(cluster,namespace,pod,container)) by(pod,cluster)"
    }
   ]
  }
 ]
}