{
 "title": "Kubernetes / Networking / Namespace (Pods)",
 "tags": [
  "kubernetes-mixin",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": ".*" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(container_network_receive_packets_total{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Rate of Bits Received",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum((8 * rate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Rate of Bits Transmitted",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum((8 * rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum((8 * rate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)"
    },
    {
     "expr": "sum((8 * rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum((8 * rate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum((8 * rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\",namespace!=\"\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) by(pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}