{
 "title": "Kubernetes / Networking / Namespace (Workload)",
 "tags": [
  "kubernetes-mixin",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": ".*" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(container_network_receive_packets_total{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "type",
    "label": "workload_type",
    "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\"}, workload_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Rate of Bits Received",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(((8 * rate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Rate of Bits Transmitted",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(((8 * rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sort_desc(sum((sum(8 * rate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(cluster,namespace,pod) * on(cluster,namespace,pod) topk(1, max(kube_pod_info{cluster=~\"$cluster\",namespace=\"$namespace\",host_network=\"false\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,workload_type,cluster))"
    },
    {
     "expr": "sort_desc(sum((sum(8 * rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(cluster,namespace,pod) * on(cluster,namespace,pod) topk(1, max(kube_pod_info{cluster=~\"$cluster\",namespace=\"$namespace\",host_network=\"false\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,workload_type,cluster))"
    },
    {
     "expr": "sort_desc(avg((sum(8 * rate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(cluster,namespace,pod) * on(cluster,namespace,pod) topk(1, max(kube_pod_info{cluster=~\"$cluster\",namespace=\"$namespace\",host_network=\"false\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,workload_type,cluster))"
    },
    {
     "expr": "sort_desc(avg((sum(8 * rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(cluster,namespace,pod) * on(cluster,namespace,pod) topk(1, max(kube_pod_info{cluster=~\"$cluster\",namespace=\"$namespace\",host_network=\"false\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,workload_type,cluster))"
    },
    {
     "expr": "sort_desc(sum((sum(1 * rate(container_network_receive_packets_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(cluster,namespace,pod) * on(cluster,namespace,pod) topk(1, max(kube_pod_info{cluster=~\"$cluster\",namespace=\"$namespace\",host_network=\"false\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,workload_type,cluster))"
    },
    {
     "expr": "sort_desc(sum((sum(1 * rate(container_network_transmit_packets_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(cluster,namespace,pod) * on(cluster,namespace,pod) topk(1, max(kube_pod_info{cluster=~\"$cluster\",namespace=\"$namespace\",host_network=\"false\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,workload_type,cluster))"
    },
    {
     "expr": "sort_desc(sum((sum(1 * rate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(cluster,namespace,pod) * on(cluster,namespace,pod) topk(1, max(kube_pod_info{cluster=~\"$cluster\",namespace=\"$namespace\",host_network=\"false\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,workload_type,cluster))"
    },
    {
     "expr": "sort_desc(sum((sum(1 * rate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by(cluster,namespace,pod) * on(cluster,namespace,pod) topk(1, max(kube_pod_info{cluster=~\"$cluster\",namespace=\"$namespace\",host_network=\"false\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,workload_type,cluster))"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(((8 * rate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(((8 * rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Workload: Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(avg(((8 * rate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Workload: Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sort_desc(avg(((8 * rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(sum((rate(container_network_receive_packets_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(sum((rate(container_network_transmit_packets_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(sum((rate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(sum((rate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]) * on(cluster,namespace,pod) group_left() topk(1, max(kube_pod_info{host_network=\"false\",cluster=~\"$cluster\"}) by(cluster,namespace,pod)) by(cluster,namespace,pod)) * on(cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\",namespace=\"$namespace\",workload=~\".+\",workload_type=~\"$type\"}) by(workload,cluster))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}