{
 "title": "Node Exporter / Nodes",
 "tags": [
  "node-exporter-mixin",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": ".*" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=\"node-exporter\",cluster=~\"$cluster\",sysname!=\"Darwin\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{job=\"node-exporter\",mode=~\"idle|iowait|steal\",instance=\"$instance\",cluster=~\"$cluster\"}[$__rate_interval])) without(mode)) / ignoring(cpu) group_left() count(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",instance=\"$instance\",cluster=~\"$cluster\"}) without(cpu,mode)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\",mode=\"idle\"}) by(cluster)",
     "legendFormat": "logical cores"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"} - node_memory_MemFree_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}) - node_memory_Buffers_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}) - node_memory_Cached_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((avg(node_memory_MemAvailable_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}) by(cluster) / avg(node_memory_MemTotal_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\"}) by(cluster)) * 100)"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\",device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(node_filesystem_size_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\",fstype!=\"\",mountpoint!=\"\"}) by(mountpoint,cluster)"
    },
    {
     "expr": "max(node_filesystem_avail_bytes{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\",fstype!=\"\",mountpoint!=\"\"}) by(mountpoint,cluster)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Network Received",
   "type": "timeseries",
   "description": "Network received (bits/s)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\",device!=\"lo\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "description": "Network transmitted (bits/s)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\",instance=\"$instance\",cluster=~\"$cluster\",device!=\"lo\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}