apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-snmp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: http://192.168.3.21:8888/helm/
      chart: opentelemetry-collector
      targetRevision: 0.162.0
      helm:
        valueFiles:
          - $values/values/otel-snmp-values.yaml
    - repoURL: https://github.com/byrn-baker/blog-sandbox-argo-cd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
