apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: suzieq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/byrn-baker/blog-sandbox-argo-cd.git
    targetRevision: main
    path: suzieq
    helm:
      valueFiles: [values.yaml, generated-values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: suzieq
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
