apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/byrn-baker/blog-sandbox-argo-cd.git
    targetRevision: main
    path: ntp
  destination:
    server: https://kubernetes.default.svc
    namespace: ntp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
